### ISSUE TITLE
Errors with sispop (RandomX algo)

### ISSUE THREAD

**Issue by 1NF1N18Y** [xiaolin1579/miningcore#25]
I added Sispop which is the same as monero to miningcore.

Error:
Connection error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Blockchain.Cryptonote.CryptonotePool.OnLoginAsync(StratumConnection connection, Timestamped1 tsRequest) in /home/pool/miningcore/src/Miningcore/Blockchain/Cryptonote/CryptonotePool.cs:line 146
   at Miningcore.Blockchain.Cryptonote.CryptonotePool.OnRequestAsync(StratumConnection connection, Timestamped1 tsRequest, CancellationToken ct) in /home/pool/miningcore/src/Miningcore/Blockchain/Cryptonote/CryptonotePool.cs:line 370
   at Miningcore.Stratum.StratumServer.OnRequestAsync(StratumConnection connection, JsonRpcRequest request, CancellationToken ct) in /home/pool/miningcore/src/Miningcore/Stratum/StratumServer.cs:line 200
   at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func4 onRequestAsync, ReadOnlySequence1 lineBuffer) in /home/pool/miningcore/src/Miningcore/Stratum/StratumConnection.cs:line 378
   at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func4 onRequestAsync, ReadOnlySequence1 lineBuffer) in /home/pool/miningcore/src/Miningcore/Stratum/StratumConnection.cs:line 378
   at Miningcore.Stratum.StratumConnection.ProcessReceivePipeAsync(CancellationToken ct, TcpProxyProtocolConfig proxyProtocol, Func`4 onRequestAsync) in /home/pool/miningcore/src/Miningcore/Stratum/StratumConnection.cs:line 281
   
   
 I used xmrig to connect:
 
![image](https://github.com/xiaolin1579/miningcore/assets/96137742/d0ead7ff-d97f-4270-bd41-e4a7c1236116)

I get this in miningcore console log

[2023-11-22 21:34:15.9560] [I] [sispop] [0HMVBJ50M4351] Banning unauthorized worker 4RDe5gBhdjpadL4Hh4bWDB2RrvQjxpESLB8tJcE1r1gEeGZo16wpC8y8KpgjJ7nSu3dwgDxXyYQmZRKYwArfvgf8BjV6KiZ for 10 sec
[2023-11-22 21:34:15.9674] [I] [sispop] [0HMVBJ50M4351] Connection closed

Please help me!

**Comment by b2d2dbone** [comment]
Maybe you forgot to open port 3032 or the difficulty is too low the api treat it as junk and keeps banning your client 
Xmrig sometimes get this weird error "end of file" try testing with rented rig after adjusting your diff 

how did you enable https on your pool could you tell me what I should do am kinda stuck 
installed certbot pointed ssl in my nginx etc and did the proxy pass configs and all am getting is https on ui but pools keeps showing the maintenance I opened an issue like 2 weeks ago you can check it out and see what I tried 

thanks

**Comment by 1NF1N18Y** [comment]
I changed the diff and it didn't work. 

when i connect I get this in the console:

[2023-11-23 11:28:24.5110] [I] [sispop] Stratum ports 0.0.0.0:2222 online
[2023-11-23 11:28:27.7508] [I] [sispop] [0HMVC1RN7CIT5] Accepting connection from ::ffff:194....
[2023-11-23 11:28:27.7622] [I] [sispop] [0HMVC1RN7CIT5] Connection from ::ffff:194.6 accepted on port 2222
[2023-11-23 11:28:37.7563] [I] [sispop] [0HMVC1RN7CIT5] Booting zombie-worker (post-connect silence)
[2023-11-23 11:28:37.7613] [I] [sispop] [0HMVC1RN7CIT5] Connection closed


when I turnoff banning 

[2023-11-22 21:13:54.9325] [E] [sispop] [0HMVBIU5562TP] Connection error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Blockchain.Cryptonote.CryptonotePool.OnLoginAsync(StratumConnection connection, Timestamped1 tsRequest) in /home/pool/miningcore/src/Miningcore/Blockchain/Cryptonote/CryptonotePool.cs:line 146
   at Miningcore.Blockchain.Cryptonote.CryptonotePool.OnRequestAsync(StratumConnection connection, Timestamped1 tsRequest, CancellationToken ct) in /home/pool/miningcore/src/Miningcore/Blockchain/Cryptonote/CryptonotePool.cs:line 370
   at Miningcore.Stratum.StratumServer.OnRequestAsync(StratumConnection connection, JsonRpcRequest request, CancellationToken ct) in /home/pool/miningcore/src/Miningcore/Stratum/StratumServer.cs:line 200
   at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func4 onRequestAsync, ReadOnlySequence1 lineBuffer) in /home/pool/miningcore/src/Miningcore/Stratum/StratumConnection.cs:line 378
   at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func4 onRequestAsync, ReadOnlySequence1 lineBuffer) in /home/pool/miningcore/src/Miningcore/Stratum/StratumConnection.cs:line 378
   at Miningcore.Stratum.StratumConnection.ProcessReceivePipeAsync(CancellationToken ct, TcpProxyProtocolConfig proxyProtocol, Func`4 onRequestAsync) in /home/pool/miningcore/src/Miningcore/Stratum/StratumConnection.cs:line 281
   
   
   (I think your nginx is broken or something. Miningcore is only backend with a api so frontend and backend are seperated.)

**Comment by b2d2dbone** [comment]
thanks for your reply 
are you willing to share your nginx + api part in your pool config copy past I will clone your configs and see where it gets me 

and good luck with sispop configs

**Comment by Lovetheminerseu** [comment]
sispop its not working with miningcore its somting with the code off randomx i have also try it i get Pool sent a malformed rpc2 job [randomx]

**Comment by 1NF1N18Y** [comment]
That is a different error than me! What is your config/coins.json?

**Comment by angelloll** [comment]
if you need help connect my on discord 417534606997192705 or go to getablocks.com for discord link
