### ISSUE TITLE
Problem when i try to connect my asic 

### ISSUE THREAD

**Issue by h8ax** [xiaolin1579/miningcore#36]
[2023-12-22 12:03:44.8392] [I] [bitcoin1] [0HN02PIRT1KGV] Connection from ::ffff:176.118.24.30:58616 accepted on port 3052
[2023-12-22 12:03:44.8392] [I] [bitcoin1] [0HN02PIRT1KGV] Using version-rolling mask 1fffe000
[2023-12-22 12:03:44.9856] [I] [bitcoin1] [0HN02PIRT1KGV] Banning unauthorized worker SS1122 for 10 sec

[2023-12-22 12:03:57.0938] [E] [bitcoin1] [0HN02PIRT1KH0] Connection error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnAuthorizeAsync(StratumConnection connection, Timestamped`1 tsRequest, CancellationToken ct) in /home/h8ax/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 146
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnRequestAsync(StratumConnection connection, Timestamped`1 tsRequest, CancellationToken ct) in /home/h8ax/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 419
   at Miningcore.Stratum.StratumServer.OnRequestAsync(StratumConnection connection, JsonRpcRequest request, CancellationToken ct) in /home/h8ax/miningcore/src/Miningcore/Stratum/StratumServer.cs:line 200
   at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func`4 onRequestAsync, ReadOnlySequence`1 lineBuffer) in /home/h8ax/miningcore/src/Miningcore/Stratum/StratumConnection.cs:line 378
   at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func`4 onRequestAsync, ReadOnlySequence`1 lineBuffer) in /home/h8ax/miningcore/src/Miningcore/Stratum/StratumConnection.cs:line 378
   at Miningcore.Stratum.StratumConnection.ProcessReceivePipeAsync(CancellationToken ct, TcpProxyProtocolConfig proxyProtocol, Func`4 onRequestAsync) in /home/h8ax/miningcore/src/Miningcore/Stratum/StratumConnection.cs:line 281

**Comment by h8ax** [comment]
maybe something wrong wiht config.json?

[2023-12-22 10:57:02.9855] [E] [bitcoin1] [0HN02OEACK7UC] Connection error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnAuthorizeAsync(StratumConnection connection, Timestamped`1 tsRequest, CancellationToken ct) in /home/h8ax/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 146
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnRequestAsync(StratumConnection connection, Timestamped`1 tsRequest, CancellationToken ct) in /home/h8ax/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 419
   at Miningcore.Stratum.StratumServer.OnRequestAsync(StratumConnection connection, JsonRpcRequest request, CancellationToken ct) in /home/h8ax/miningcore/src/Miningcore/Stratum/StratumServer.cs:line 200
   at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func`4 onRequestAsync, ReadOnlySequence`1 lineBuffer) in /home/h8ax/miningcore/src/Miningcore/Stratum/StratumConnection.cs:line 378
   at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func`4 onRequestAsync, ReadOnlySequence`1 lineBuffer) in /home/h8ax/miningcore/src/Miningcore/Stratum/StratumConnection.cs:line 378
   at Miningcore.Stratum.StratumConnection.ProcessReceivePipeAsync(CancellationToken ct, TcpProxyProtocolConfig proxyProtocol, Func`4 onRequestAsync) in /home/h8ax/miningcore/src/Miningcore/Stratum/StratumConnection



.cs:line 281


{
  "logging": {
    "level": "info",
    "enableConsoleLog": true,
    "enableConsoleColors": true,
    "logFile": "miningcore.log",
    "logBaseDirectory": "/home/mynode/miningcore/logs/",
    "perPoolLogFile": false
  },
  "banning": {
    "banOnJunkReceive": false,
    "banOnInvalidShares": false
  },
  "notifications": {
    "enabled": true,
    "email": {
      "host": "smtp.example.com",
      "port": 587,
      "user": "user",
      "password": "password",
      "fromAddress": "info@yourpool.org",
      "fromName": "pool support"
    },
    "admin": {
      "enabled": false,
      "emailAddress": "user@example.com",
      "notifyBlockFound": true
    }
  },
  "persistence": {
    "postgres": {
      "host": "127.0.0.1",
      "port": 5432,
      "user": "miningcore",
      "password": "mypassword",
      "database": "miningcore"
    }
  },
  "paymentProcessing": {
    "enabled": true,
    "interval": 180,
    "shareRecoveryFile": "recovered-shares.txt"
  },
  "api": {
    "enabled": true,
    "listenAddress": "*",
    "port": 4000
  },
  "pools": [{
    "id": "bitcoin1",
    "enabled": true,
    "coin": "bitcoin",
    "address": "my wallet"
    "rewardRecipients": [{
      "address": "my waleet"
      "percentage": 1.5
    }],
    "blockRefreshInterval": 400,
    "jobRebroadcastTimeout": 10,
  "clientConnectionTimeout": 600,
    "banning": {
      "enabled": true,
      "time": 600,
      "invalidPercent": 50,
      "checkThreshold": 50
    },
    "ports": {
      "3052": {
        "listenAddress": "*",
        "difficulty": 0.02,
        "tls": false,
        "varDiff": {
          "minDiff": 0.01,
          "maxDiff": null,
          "targetTime": 15,
          "retargetTime": 90,
          "variancePercent": 30,
          "maxDelta": 500
        }
      }
    },
    "daemons": [{
      "host": "127.0.0.1",
      "port": 8332,
      "user": "rpcuser,
      "password": rpcpassword,
    }],
    "paymentProcessing": {
      "enabled": true,
      "minimumPayment": 0.01,
      "payoutScheme": "PPLNS",
      "payoutSchemeConfig": {
        "factor": 2.0
      }
    }
  }]
}

**Comment by xiaolin1579** [comment]
try 
https://github.com/xiaolin1579/miningcore/pull/23
https://github.com/xiaolin1579/miningcore/pull/22
