### ISSUE TITLE
Application crashing during start-up

### ISSUE THREAD

**Issue by gdiscord** [xiaolin1579/miningcore#45]
I am trying to setup the software for the first time with Arion coin (https://github.com/arioncoin/arioncoin). Since the coin is based off of dash codebase (X11), I copied the dash entry in coin.json and inserted the Arion specific values.

However, whenever I start the application the following exception is thrown and the program quits immediately.

[2024-01-20 16:51:40.4837] [I] [arion5] Starting Pool ... 
[2024-01-20 16:51:40.4928] [I] [arion5] ExtraNonceProvider using 4 bits for instance id, 28 bits for 268435455 values, instance id = 0x1 
[2024-01-20 16:51:40.5009] [I] [arion5] Starting Job Manager ... 
[2024-01-20 16:51:40.6969] [I] [Core] API Access to /api/admin restricted to 127.0.0.1,::1,::ffff:127.0.0.1 
[2024-01-20 16:51:40.6969] [I] [Core] API Access to /metrics restricted to 127.0.0.1,::1,::ffff:127.0.0.1 
[2024-01-20 16:51:40.7462] [F] [Diagnostics] Application startup exception System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Program.<>c.<Main>b__0_9(JsonOptions options) in /home/pool/miningcore/src/Miningcore/Program.cs:line 188
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Mvc.MvcCoreMvcOptionsSetup.Configure(MvcOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app)
   at Miningcore.Program.<>c__DisplayClass0_0.<Main>b__5(IApplicationBuilder app) in /home/pool/miningcore/src/Miningcore/Program.cs:line 240
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass17_0.<Configure>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)    at Miningcore.Program.<>c.<Main>b__0_9(JsonOptions options) in /home/pool/miningcore/src/Miningcore/Program.cs:line 188
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Mvc.MvcCoreMvcOptionsSetup.Configure(MvcOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app)
   at Miningcore.Program.<>c__DisplayClass0_0.<Main>b__5(IApplicationBuilder app) in /home/pool/miningcore/src/Miningcore/Program.cs:line 240
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass17_0.<Configure>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
[2024-01-20 16:51:40.8170] [I] [Lifetime] Application is shutting down... 
[2024-01-20 16:51:40.8170] [I] [arion5] Waiting for daemons to come online ... 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Program.<>c.<Main>b__0_9(JsonOptions options) in /home/pool/miningcore/src/Miningcore/Program.cs:line 188
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Mvc.MvcCoreMvcOptionsSetup.Configure(MvcOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app)
   at Miningcore.Program.<>c__DisplayClass0_0.<Main>b__5(IApplicationBuilder app) in /home/pool/miningcore/src/Miningcore/Program.cs:line 240
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass17_0.<Configure>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Miningcore.Program.Main(String[] args) in /home/pool/miningcore/src/Miningcore/Program.cs:line 252
Cluster cannot start. Good Bye!

Here's the Arion entry I've made in **coins.json**
_"arion": {
        "name": "Arion Coin",
        "canonicalName": "arion",
        "symbol": "ARION",
        "family": "bitcoin",
        "website": "https://arioncoin.com",
        "market": "https://www.finexbox.com/market/pair/ARION-USDT.html",
        "twitter": "https://twitter.com/ARION_COIN",
        "telegram": "https://t.me/arioncoin",
        "discord": "https://discord.gg/gK632Af",
        "coinbaseHasher": {
            "hash": "sha256d"
        },
        "headerHasher": {
            "hash": "x11"
        },
        "blockHasher": {
            "hash": "reverse",
            "args": [
                {
                    "hash": "x11"
                }
            ]
        },
        "hasMasterNodes": true,
        "explorerBlockLink": "https://arion.ccore.online/block/{0}",
        "explorerTxLink": "https://arion.ccore.online/transaction/{0}",
        "explorerAccountLink": "https://arion.ccore.online/address/{0}"
    }_

And here the **pool.json**
_{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "Integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": true,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "miningcore",
            "password": "miningcore",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "pools": [{
        "id": "arion5",
        "enabled": true,
        "coin": "arioncoin",
        "address": "xxx",
        "rewardRecipients": [{
            "address": "xxx",
            "percentage": 0
        }],
        "blockRefreshInterval": 500,
        "jobRebroadcastTimeout": 10,
        "clientConnectionTimeout": 600,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 50
        },
        "ports": {
            "5062": {
                "listenAddress": "0.0.0.0",
                "difficulty": 1024,
                "name": "ASIC Mining",
                "varDiff": {
                    "minDiff": 512,
                    "targetTime": 15,
                    "retargetTime": 90,
                    "variancePercent": 30
                }
            }
        },
        "daemons": [{
            "host": "127.0.0.1",
            "port": 2121,
            "user": "user",
            "password": "password"
        }],
        "paymentProcessing": {
            "enabled": true,
            "minimumPayment": 0.5,
            "payoutScheme": "SOLO",
            "payoutSchemeConfig": {
                "factor": 2.0
            }
        }
    }]
}_

**Comment by gdiscord** [comment]
fixed by adding api object to pool.json
